/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.14 and the DSP System Toolbox 8.2.
 *
 * Generated on: 22-Jul-2013 18:51:13
 *
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 15
 * Stable              : Yes
 * Linear Phase        : No
 * Arithmetic          : fixed
 * Numerator           : s16,14 -> [-2 2)
 * Denominator         : s16,14 -> [-2 2)
 * Scale Values        : s16,14 -> [-2 2)
 * Input               : s16,15 -> [-1 1)
 * Section Input       : s16,9 -> [-64 64)
 * Section Output      : s16,11 -> [-16 16)
 * Output              : s16,11 -> [-16 16)
 * State               : s16,15 -> [-1 1)
 * Numerator Prod      : s32,29 -> [-4 4)
 * Denominator Prod    : s32,29 -> [-4 4)
 * Numerator Accum     : s34,29 -> [-16 16)
 * Denominator Accum   : s34,29 -> [-16 16)
 * Round Mode          : convergent
 * Overflow Mode       : wrap
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2012a/extern/include/tmwtypes.h 
 */
#define MWSPT_NSEC 31
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,2,1 };
const int16_T NUM[MWSPT_NSEC][3] = {
  {
     6898,      0,      0 
  },
  {
    16384, -32768,  16384 
  },
  {
     6262,      0,      0 
  },
  {
    16384, -32768,  16384 
  },
  {
     5742,      0,      0 
  },
  {
    16384, -32768,  16384 
  },
  {
     5314,      0,      0 
  },
  {
    16384, -32768,  16384 
  },
  {
     4960,      0,      0 
  },
  {
    16384, -32768,  16384 
  },
  {
     4667,      0,      0 
  },
  {
    16384, -32768,  16384 
  },
  {
     4423,      0,      0 
  },
  {
    16384, -32768,  16384 
  },
  {
     4223,      0,      0 
  },
  {
    16384, -32768,  16384 
  },
  {
     4059,      0,      0 
  },
  {
    16384, -32768,  16384 
  },
  {
     3926,      0,      0 
  },
  {
    16384, -32768,  16384 
  },
  {
     3822,      0,      0 
  },
  {
    16384, -32768,  16384 
  },
  {
     3744,      0,      0 
  },
  {
    16384, -32768,  16384 
  },
  {
     3689,      0,      0 
  },
  {
    16384, -32768,  16384 
  },
  {
     3657,      0,      0 
  },
  {
    16384, -32768,  16384 
  },
  {
     7729,      0,      0 
  },
  {
    16384, -16384,      0 
  },
  {
    16384,      0,      0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,2,1 };
const int16_T DEN[MWSPT_NSEC][3] = {
  {
    16384,      0,      0 
  },
  {
    16384,   3504,  14711 
  },
  {
    16384,      0,      0 
  },
  {
    16384,   3181,  11846 
  },
  {
    16384,      0,      0 
  },
  {
    16384,   2917,   9503 
  },
  {
    16384,      0,      0 
  },
  {
    16384,   2699,   7573 
  },
  {
    16384,      0,      0 
  },
  {
    16384,   2520,   5977 
  },
  {
    16384,      0,      0 
  },
  {
    16384,   2370,   4653 
  },
  {
    16384,      0,      0 
  },
  {
    16384,   2247,   3557 
  },
  {
    16384,      0,      0 
  },
  {
    16384,   2145,   2652 
  },
  {
    16384,      0,      0 
  },
  {
    16384,   2062,   1912 
  },
  {
    16384,      0,      0 
  },
  {
    16384,   1994,   1315 
  },
  {
    16384,      0,      0 
  },
  {
    16384,   1941,    846 
  },
  {
    16384,      0,      0 
  },
  {
    16384,   1902,    493 
  },
  {
    16384,      0,      0 
  },
  {
    16384,   1874,    246 
  },
  {
    16384,      0,      0 
  },
  {
    16384,   1857,    101 
  },
  {
    16384,      0,      0 
  },
  {
    16384,    926,      0 
  },
  {
    16384,      0,      0 
  }
};
